#! /bin/sh

sxhkd &
nitrogen --restore 
~/.config/polybar/polybar-launch.sh 

bspc monitor -d 1 2 3 4 5 6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 3
bspc config window_gap 10
bspc config normal_border_color "4C566a"
bspc config focused_border_color "5e81ac"
bspc config presel_border_color "5e81ac"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
